bleachbit -c google_chrome.cache
bleachbit -c google_chrome.cookies
bleachbit -c google_chrome.session
bleachbit -c chromium.cache
bleachbit -c chromium.cookies
bleachbit -c chromium.current_session
bleachbit -c firefox.cache
bleachbit -c firefox.cookies
bleachbit -c system.cache
bleachbit -c system.memory
bleachbit -c apt.clean
